version: '3.8'

services:
  postgres:
    image: postgres:15 # Use the latest stable version of PostgreSQL
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin       # Username for the database
      POSTGRES_PASSWORD: password # Password for the database
      POSTGRES_DB: p3ai          # Default database to be created
    ports:
      - "5432:5432"              # Expose the PostgreSQL service on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data across restarts

volumes:
  postgres_data:
