'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { clsx } from "clsx";
import DashboardLayout from "@/components/layouts/dashboard-layout";
import { useAtom } from "jotai";
import { contractAtom, web3Atom } from "@/store/global.store";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "AI Startup Landing Page  • Spectron Labs",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    
    const [contract,] = useAtom(contractAtom);
    const [web3,] = useAtom(web3Atom);

    const getAIIdentities = async () => {

        let agents = contract?.methods.getUserAIAgents(web3?.defaultAccount).call();
        console.log(agents,"++++");
        console.log(web3?.currentProvider)
    }

    useEffect(()=> {
        getAIIdentities();
    })

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={clsx(inter.className, "antialiased")}>
                <DashboardLayout loading={false}>
                    {children}
                </DashboardLayout>
            </body>
        </html>
    );
}
